Add lint job to Github actions and fixed lint errors (#36)
* Add lint job golangci/golangci-lint-action@v2.5.2 and fixed lint errors.

Fixed next lint errors:
internal/login/login.go:122:19: Error return value of server.Shutdown is not checked (errcheck)
main.go:30:23: Error return value of viper.SafeWriteConfig is not checked (errcheck)
main.go:31:20: Error return value of viper.ReadInConfig is not checked (errcheck)
main.go:63:14: Error return value of root.Execute is not checked (errcheck)
internal/play/play.go:52:3: ineffectual assignment to err (ineffassign)
internal/common.go:51:10: SA1015: using time.Tick leaks the underlying ticker, consider using it only in endless functions, tests and the main package, and use time.NewTicker here (staticcheck)

* Update .github/workflows/test.yml - removed name for golangci/golangci-lint-action

Co-authored-by: Brian Strauch <bstrauch24@gmail.com>

* Update internal/login/login.go -make staticcheck happy without err check

Co-authored-by: Brian Strauch <bstrauch24@gmail.com>

* Update main.go - replaced err !=nill check with cobra.CheckErr()

Co-authored-by: Brian Strauch <bstrauch24@gmail.com>

* Update main.go - removed err check for viper.ReadInConfig() because of bad UX

Co-authored-by: Brian Strauch <bstrauch24@gmail.com>

* Updated main.go - unused imports and undefined: err

* Updated play/play.go - add another check in the else block and delete the check below the entire if/else because otherwise, staticcheck reports an error

* Updated go.mod and go.sum - removed unused dependencies

Co-authored-by: Brian Strauch <bstrauch24@gmail.com>